### ISSUE TITLE
Upgrade and extend linter

### ISSUE THREAD

**Issue by mattdell** [DeloitteDigitalUK/react-redux-starter-app#29]
I'd like to start an effort to get our projects using the same style conventions and I feel that this repository is an excellent starting point and testing ground.

Two things to start with
1. eslint-config-airbnb is on v12.0.0; ours is on v10.0.0
2. eslint-plugin-import is on v1.16.0; ours is on v1.13.0

Additionally, I'd like to review some of the linters I've been using over the past year and see what the consensus is.

**Comment by michael-martin** [comment]
Totally support the idea! 👍

**Comment by michael-martin** [comment]
Closing now as Matt's PR resolved this.
