### ISSUE TITLE
Git history of react-redux

### ISSUE THREAD

**Issue by vitkon** [DeloitteDigitalUK/react-redux-starter-app#3]
can we remove git history of react-redux? Is there a benefit of storing them?
Currently it shows 903 commits in the repo.

**Comment by michael-martin** [comment]
Makes sense, yep. May mean recreating this repo again (Which loses the issues), but I'll take a look now before the repo really has anything in it!

**Comment by michael-martin** [comment]
Done now. History crushed into 1 commit for a clean start now.
