### ISSUE TITLE
/weather does not load and throws an error

### ISSUE THREAD

**Issue by mattdell** [DeloitteDigitalUK/react-redux-starter-app#31]
When building from master the following happens when navigating to http://localhost:3000/weather

![screen shot 2016-10-26 at 17 08 35](https://cloud.githubusercontent.com/assets/2536442/19734304/f5283bf2-9b9e-11e6-9eaf-5fc084200167.png)

**Comment by michael-martin** [comment]
Meaning to remove the weather pieces altogether. Really we just want one example of each feature that a standard app might want to see (e.g. API calls, form validation etc.). I don't think the weather adds anything not already covered in the Github example feature.

**Comment by mattdell** [comment]
😄 

Well, I've fixed it if you'd like the fix ☝️

**Comment by michael-martin** [comment]
Ah perfect, merging! I'll still remove it eventually, but thanks for fixing until then :D
